---
- hosts: all
  remote_user: gmkbabu
  become: yes
  tasks:
    - name: download the java
      command: wget -q -o http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-i586.tar.gz dest=/tmp/
    - name: create the directory
      command: mkdir /usr/local/java state=directory
    - name: unpack the java 
      unarchive: src=/tmp/jdk-8u161-linux-i586.tar.gz dest=/usr/local/java copy=no
