---
- hosts: 192.168.56.15
  remote_user: gmkbabu
  become: yes
  tasks:
    - name: download the jdk
      command: wget "http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz" --no-cookies --no-check-certificate --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' dest=/tmp/ mod=0777 
    
    - name: create the folder
      command: sudo mkdir /usr/local/java state=directory 


    - name: unpack the jdk file
      unarchive: src=/tmp/jdk-8u161-linux-x64.tar.gz dest=/usr/local/java/ copy=no
