---
- hosts: all
  tasks:
    - group:
        name: "evens"
        state: present
    - user:
        name: "{{ item }}"
        state: present
        groups: "evens"
      with_sequence: start=0 end=32 formt=testuser%02x
    - file:
        dest: "/home/gmkbabu/{{ item }}"
        state: directory
      with_sequence: start=4 end=16 stride=2
    - group:
        name: "group{{ item }}"
        state: present
      with_sequence: count=4  
