---
- hosts: all
  vars:
     some_list:
          alpha: [ 'a', 'b', 'c', 'd' ]
          number: [ 1, 2, 3, 4 ]
  tasks:
    - name: indexed loop demo
      debug: msg="at array position {{ item.0 }} there is a value {{ item.1 }}"
      with_index.items:
           - "{{ some_list }}"
