---
- hosts: all
  vars:
    alpha: [ 'a', 'b', 'c', 'd' ]
    number: [ 1, 2, 3, 4 ]
  tasks:
     - debug:
         msg: "{{ item.0 }} and {{ item.1 }}"
       with_together:
            - "{{ alpha }}"
            - "{{ number }}"
